language: python
python:
	-"2.7"

install: "pip  install -r requirements.txt"

before-script:
	-autopep8 -ir *
	-flake8 --max-complexity=3 --exclude=*.txt,*.md --max-line-length=200 *

script:
	- lettuce AceptanceTest
	- cd UnitTest
	- python TestCase.python
	- coverage run --branch TestCase.python
	- coverage report -m
